### ISSUE TITLE
can not found conf.py

### ISSUE THREAD

**Issue by rexzhang** [beeware/galley#4]
broke at max osx 10.10, setup by local git repo

```
Rex-mbp:docs rex$ pwd
/Users/rex/pycode/galley/docs
```

```
Rex-mbp:docs rex$ galley
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/galley-0.1.0.dev20150122015705-py2.7.egg/galley/worker.py", line 177, in sphinx_worker
    warningiserror, tags)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/application.py", line 125, in __init__
    confoverrides or {}, self.tags)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/config.py", line 240, in __init__
    execfile_(filename, config)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/util/pycompat.py", line 83, in execfile_
    f = open(filepath, 'rbU')
IOError: [Errno 2] No such file or directory: 'conf.py'
```

**Comment by freakboy3742** [comment]
I'm going to guess this is related to using a beta version of Sphinx - it might even be a bug in Sphinx itself (since the stack trace is being raised inside Sphinx, not Galley). Can you try running with a stable release  of Sphinx?

**Comment by rexzhang** [comment]
i am try again with Sphinx v1.2.3
```
Rex-mbp:docs rex$ galley
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/galley-0.1.0.dev20150122015705-py2.7.egg/galley/worker.py", line 177, in sphinx_worker
    warningiserror, tags)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/Library/Python/2.7/site-packages/sphinx/util/pycompat.py", line 83, in execfile_
    f = open(filepath, 'rbU')
IOError: [Errno 2] No such file or directory: 'conf.py'
```

**Comment by ThomasG77** [comment]
Trying it, I encountered the same issue.
It's because you need to run galley from the directory above docs. This `docs` directory must contain a `conf.py` file
Imagine after install you want to try to see galley doc, you will do

```
git clone https://github.com/pybee/galley.git
cd galley
galley
```

I've tried previously
```
git clone https://github.com/pybee/galley.git
cd galley
cd docs
galley
```
and I had the issue

**Comment by freakboy3742** [comment]
Between in-editor Markdown previews and Mkdocs live reload, the need for a standalone app for docs preview is much less than it once was. As a result, we're archiving this repo.
